name: app_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  intl: ^0.18.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  audioplayers: ^5.2.0
  flutter_gif: any
  flutter_native_splash: ^2.3.4

  flutter_lints: ^2.0.3
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "0.13.1"


flutter_launcher_icons:
  image_path: "assets/BEANS.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/BEANS.png"
  min_sdk_android: 21



  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/BEANS.png


flutter_native_splash:
  background_image: "assets/images/BEANS.png"
  android_12:
    background_image: "assets/images/BEANS.png"


