//this dear partner is where the THEMES are going to go
//Themes to add: light, dark, colorblind, aaaaaaannnnd...
//CUSTOM!!! Debating whether to add a custom built list of colors or 
//somehow figure out how to add an RGB slider but we'll see...
//...we shall see...


class poop{}